name: wheel_we_meet
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.13.6
  cloud_functions: ^4.5.8
  equatable: ^2.0.5
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.8
  firebase_storage: ^11.5.6
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^16.2.0
  geolocator: ^10.1.0
  get_it: ^7.6.4
  http: ^1.1.2
  image_picker: ^1.0.5
  intl: ^0.18.0
  in_app_purchase: ^3.1.11
  in_app_review: ^2.0.8
  mapbox_maps_flutter: ^0.5.1
  permission_handler: ^11.1.0
  rxdart: ^0.27.7
  timeago: ^3.6.0
  wolt_modal_sheet: ^0.2.0
  workmanager: ^0.5.2

  flutter_mapbox_navigation:
    path: ../flutter_mapbox_navigation

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - .env
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
